FROM python:3.9

WORKDIR /code
COPY dataPredicting.py predictor.py
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

CMD  [ "python3", "predictor.py", "demeter", "historical_data", "model_coefficient_new", "predict_data" ]