FROM python:3.9

WORKDIR /code
COPY dataModelling.py trainer.py
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

CMD  [ "python3", "trainer.py", "demeter", "historical_data", "model_coefficient" ]